# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhjZpUtZIjGb2UckP-uwDnWLYlNMaydM
"""

import joblib
import numpy as np
import streamlit as st


@st.cache_resource
def load_assets():
    mlp = joblib.load("mlp_model.joblib")
    scaler = joblib.load("scaler.joblib")
    feature_names = joblib.load("feature_names.joblib")
    return mlp, scaler, feature_names


mlp, scaler, feature_names = load_assets()



# Create a two-column layout for inputs
col1, col2 = st.columns(2)
input_values = []

for idx, feature in enumerate(feature_names):
    target_col = col1 if idx % 2 == 0 else col2

    # Binary selection for ocean proximity dummy variables
    if "ocean_proximity" in feature:
        val = target_col.selectbox(f"{feature}", options=[0, 1], index=0)
    else:
        val = target_col.number_input(f"{feature}", value=0.0)

    input_values.append(val)

st.markdown("---")
if st.button("🚀 Predict House Value", use_container_width=True):
    # Scale user input using the fitted scaler
    raw_input = np.array([input_values])
    scaled_input = scaler.transform(raw_input)

    # Make prediction
    prediction = mlp.predict(scaled_input)[0]

    # Display result
    st.metric(
        label="Estimated House Value",
        value=f"${prediction:,.2f}",
    )