# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhjZpUtZIjGb2UckP-uwDnWLYlNMaydM
"""

import joblib
import numpy as np
import streamlit as st


@st.cache_resource
def load_assets():
    mlp = joblib.load("mlp_model.joblib")
    scaler = joblib.load("scaler.joblib")
    return mlp, scaler


mlp, scaler = load_assets()



# Create a two-column layout for inputs
col1, col2 = st.columns(2)
input_values = []


st.markdown("---")
if st.button("🚀 Predict House Value", use_container_width=True):
    # Scale user input using the fitted scaler
    raw_input = np.array([input_values])
    scaled_input = scaler.transform(raw_input)

    # Make prediction
    prediction = mlp.predict(scaled_input)[0]

    # Display result
    st.metric(
        label="Estimated House Value",
        value=f"${prediction:,.2f}",
    )
